### ISSUE TITLE
Can specific attributes in a model be tracked when updating?

### ISSUE THREAD

**Issue by jztb** [bodrovis/SitePoint-PublicActivity#1]
Say for example, a class Post, has attributes title, image, link, content. If a user updates say a typing error in the content of a particular post, how can public_activity enable this in the view?
eg. John has updated the content of the post "Greek exits Eurozone" a minute ago

If two or more attributes are changed and updated at the same update action, how can public_activity show that too?

**Comment by bodrovis** [comment]
I believe you'd go for https://github.com/airblade/paper_trail in this case. I have a tutorial about it as well. http://www.sitepoint.com/versioning-papertrail/

**Comment by RailsCod3rFuture** [comment]
Hello, Bodrovis. I'm currently receiving a ActiveRecord::UnknownAttributeError (unknown attribute 'photo' for PublicActivity::Activity.): in my create method for posts_controller.rb. Do you have a solution to resolving this error?

**Comment by bodrovis** [comment]
@RailsCod3rFuture I wish I were a magician with a solution to each and every problem, but unfortunately I am not. :( Could you please follow the steps here https://github.com/bodrovis/Sitepoint-source/blob/master/CONTRIBUTING.md to create a separate issue and describe your problem along with pasting some code? I am closing this one as it is related to another question.
